card/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path('addtocard/<str:pk>', views.addtocard, name='add-to'),

    path('', views.card, name='cart'),
    path('removeitem/<str:pk>', views.cardremove, name='remove-item'),

]

searchservice/urls.py
from django.contrib import admin
from django.urls import path,include
from searchservice.settings import MEDIA_ROOT

from django.conf import settings


from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
urlpatterns = [

    path('securelogin/', admin.site.urls),
    path('', include('service.urls')),
    path('account/', include('accounts.urls')),
    path('card/', include('card.urls')),
    
    path('order/', include('order.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="users/reset_password.html"),
         name='reset_password'),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="users/reset_password_send.html"),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/reset.html"),
         name='password_reset_confirm'),


    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/reset_password_complete.html"),
         name='password_reset_complete'),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

service/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path('', views.index, name='index'),

    path('category/<str:pk>', views.categoryservice, name='category'),

    path('categorydetail/<str:pk>', views.categoryDetail, name='categorydetail'),
    path('categoryfinal/<str:pk>', views.categoryfinal, name='categoryfinal'),

    path('createservice', views.createservice, name='create-service'),

    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),


    path('servicedetail/<str:pk>', views.serviceDetail, name='show-detail'),

    path('submitreview/<str:service_id>',
         views.submit_review, name="submit-review"),
]

order/models.py
from django.db import models

# Create your models here.
import uuid
from service.models import Service


class Payement(models.Model):

    owner = models.ForeignKey(
        "accounts.Account", models.CASCADE, related_name="orderr")

    payement_id = models.CharField(max_length=100)
    payement_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return self.payement_id


class Order(models.Model):

    STATUS = {
        ('New', 'New'),
        ('Accepted', 'accepted'),
        ('Completed', 'Completed'),
        ('Cenceled', 'Cenceled'),

    }

    owner = models.ForeignKey(
        "accounts.Account", models.CASCADE, related_name="orderrr")

    payement = models.ForeignKey(
        Payement, on_delete=models.SET_NULL, blank=True, null=True)

    order_number = models.CharField(max_length=20)

    wilaya = models.CharField(max_length=50)

    adress_line_1 = models.CharField(max_length=50)

    adress_line_2 = models.CharField(max_length=50, blank=True)

    state = models.CharField(max_length=50)

    city = models.CharField(max_length=50)

    order_note = models.CharField(max_length=100, blank=True)

    order_total = models.FloatField(default=0)
    tax = models.FloatField(default=0)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(max_length=20, blank=True)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    uploaded_at = models.DateTimeField(auto_now=True)

    def __str__(self):

        return self.wilaya


class OrderService(models.Model):

    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    owner = models.ForeignKey(
        "accounts.Account", models.CASCADE, related_name="orderrre")

    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True)

    user = models.ForeignKey(
        "accounts.Account", models.CASCADE, related_name="orderrree")

    ordered = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    uploaded_at = models.DateTimeField(auto_now=True)

    def __str__(self):

        return self.service.Service_name

service/models.py
from email.policy import default
from django.db import models

# Create your models here.

from django.db import models

# Create your models here.

import uuid


class Wilaya(models.Model):

    wilaya_name = models.CharField(max_length=200)

    wilaya_matricule = models.IntegerField()

    created = models.DateTimeField(auto_now_add=True)

    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):

        return self.wilaya_name


class baladiya(models.Model):

    baladiya_name = models.CharField(max_length=200)

    wilaya = models.ForeignKey(Wilaya, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)

    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):

        return self.baladiya_name


class Category(models.Model):

    Category_name = models.CharField(max_length=200)

    description_cat = models.TextField(max_length=500, blank=True)

    wilaya = models.ForeignKey(Wilaya, on_delete=models.CASCADE)

    baladiya = models.ForeignKey(baladiya, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)

    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):

        return self.Category_name


class Service(models.Model):

    owner = models.ForeignKey(
        "accounts.Account", models.CASCADE, related_name="Sevice")

    Service_name = models.CharField(max_length=200)

    description = models.TextField(max_length=500, blank=True)

    image = models.ImageField(upload_to='photos/Service')

    is_avalaible = models.BooleanField(default=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    wilaya = models.ForeignKey(Wilaya, on_delete=models.CASCADE)

    baladiya = models.ForeignKey(baladiya, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)

    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):

        return self.category.wilaya.wilaya_name


class Createservice(models.Model):

    user = models.ForeignKey(
        "accounts.Account", models.CASCADE, related_name="Sev")

    Service_name = models.CharField(max_length=200)

    description = models.TextField(max_length=500, blank=True)

    images = models.ImageField(upload_to='photos/Ser')

    your_sertificate = models.ImageField(upload_to='photos/Competence')

    is_avalaible = models.BooleanField(default=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    baladiya = models.ForeignKey(baladiya, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)

    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):

        return self.category.wilaya.wilaya_name


class ReviewRating(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    owner = models.ForeignKey(
        "accounts.Account", models.CASCADE, related_name="Sevicess")
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(null=True, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)

    status = models.BooleanField(default=True)

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner', 'service']]

    def __str__(self):

        return self.owner.email

service/forms.py
from django import forms
from django.forms import ModelForm
from .models import Createservice
from .models import Category, ReviewRating, baladiya


class Serviceform(ModelForm):

    class Meta:

        model = Createservice

        fields = ['Service_name',

                  'description', 'your_sertificate', 'images', 'baladiya', 'category']

    def __init__(self, *args, **kwargs):

        self.user = kwargs.pop('user')

        super(Serviceform, self).__init__(*args, **kwargs)

        print(self.user)

        if self.user is not None:

            self.fields['baladiya'].queryset = baladiya.objects.filter(

                wilaya=self.user.wilaya)

            self.fields['category'].queryset = Category.objects.filter(

                wilaya=self.user.wilaya)

            #self.fields['category'].queryset = Category.objects.none()

            if 'baladiya' in self.data:

                try:

                    baladiya_id = int(self.data.get('baladiya'))
                    self.fields['category'].queryset = Category.objects.filter(
                        baladiya_id=baladiya_id).order_by('Category_name')

                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset


class reviews(ModelForm):
    class Meta:
        model = ReviewRating

        fields = ['subject', 'review', 'rating']

service/views.py
from django.shortcuts import render, redirect


# Create your views here.

from .models import Service, Category, Wilaya, Createservice, baladiya
from .forms import Serviceform
from service import forms

from django.contrib.auth.decorators import login_required

from order.models import OrderService
from .models import ReviewRating
from.forms import reviews


def index(request):

    service = Service.objects.all()

    context = {'service': service}

    return render(request, 'services/index.html', context)


def categoryservice(request, pk):

    wilaya = Wilaya.objects.get(id=pk)

    #category = Category.objects.filter(wilaya=wilaya)
    balad = baladiya.objects.filter(wilaya=wilaya)

    service = Service.objects.filter(wilaya=wilaya)

    context = {"baladiya": balad, "service": service, "wilaya": wilaya}

    return render(request, 'services/categoryall.html', context)


def categoryDetail(request, pk):

    #category = Category.objects.get(id=pk)
    
    balad = baladiya.objects.get(id=pk)
    
    category = Category.objects.filter(baladiya=balad)

    service = Service.objects.filter(baladiya=balad)

    counter = service.count()

    context = {"service": service, "counter": counter, "category": category}

    return render(request, 'services/categoryproduct.html', context)


def categoryfinal(request, pk):

    category = Category.objects.get(id=pk)

    service = Service.objects.filter(category=category)

    context = {"service": service}

    return render(request, 'services/categoryfinal.html', context)


@login_required
def createservice(request):

    if request.method == 'POST':

        user = request.user

        services = Serviceform(request.POST, request.FILES, user=user)

        if services.is_valid():

            servicess = services.save(commit=False)

            servicess.user = user

            servicess.save()

            return redirect('index')

    else:

        user = request.user

        services = Serviceform(user=user)

    context = {"service": services}

    return render(request, 'services/createservice.html', context)


def load_cities(request):

    baladiya_id = request.GET.get('baladiya_id')

    cities = Category.objects.filter(baladiya_id=baladiya_id).all()

    return render(request, 'services/city_dropdown_list_options.html', {'cities': cities})


def serviceDetail(request, pk):
    service = Service.objects.get(id=pk)

    if request.user.is_authenticated:

        orderproduct = OrderService.objects.filter(
            owner=request.user, service=service).exists()

    else:

        orderproduct = None

    #show = service.reviewrating_set.all()
    show = ReviewRating.objects.filter(service=service)

    Avg = 0
    total = 0
    count = 0

    reviewaverage = ReviewRating.objects.filter(service=service)
    for average in reviewaverage:
        total += average.rating
        count += 1
    if reviewaverage:
        Avg = total/count

    context = {"service": service, "show": show,
               "orderproduct": orderproduct, "Avg": Avg}

    return render(request, 'services/servicesdetail.html', context)


def submit_review(request, service_id):

    url = request.META.get('HTTP_REFERER')

    if request.method == "POST":

        try:
            reviewss = ReviewRating.objects.get(
                owner=request.user, service__id=service_id)

            forms = reviews(request.POST, instance=reviewss)

            forms.save()

            return redirect(url)

        except ReviewRating.DoesNotExist:

            forms = reviews(request.POST)

            if forms.is_valid():

                formss = forms.save(commit=False)

                formss.owner = request.user

                formss.service_id = service_id

                formss.ip = request.META.get('REMOTE_ADDR')

                formss.save()

                return redirect(url)

service/templates/services/categoryall.html
{% extends 'homepages.html' %}

{% block content %}




<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container">
        <h2 class="title-page">Our Services</h2>
        
    </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->
    
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-md-3">
            
    <div class="card">
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">BALADIYA</h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" >

                <div class="card-body">

                    <ul class="list-menu">

                        {% for cat in baladiya %}

                    <li><a href="{% url 'categorydetail' cat.id %}"> {{cat.baladiya_name}} </a></li>
                    
                    {% endfor %}

                    </ul>

                </div> <!-- card-body.// -->

            </div>

        </article> <!-- filter-group  .// -->

    </div> <!-- card.// -->
     
        </aside> <!-- col.// -->
        <main class="col-md-9">
            
    <header class="border-bottom mb-4 pb-3">
        <div class="form-inline">
            <span class="mr-md-auto"> {{wilaya.wilaya_name}} services  </span>

        </div>
</header><!-- sect-heading -->
            
    
          
        

    <div class="row">
        {% for donc in service %}

    
        <div class="col-md-4">

            <figure class="card card-product-grid">
                
                <div class="img-wrap"> 

                    <img src="{{donc.image.url}}">

                </div> <!-- img-wrap.// -->

                <figcaption class="info-wrap">
                    <div class="fix-height">
                        <a href="#" class="title"></a>
                        <div class="price-wrap mt-2">
                            <span class="price">  {{donc.Service_name}}</span>
                            <br>
                            <span class="price">baladiya: {{donc.baladiya}}</span>

                            <br>

                            <span class="price">{{donc.owner.first_name}} </span>
                            <span class="price">{{donc.owner.last_name}} </span>
                            <br>


                        </div> <!-- price-wrap.// -->

                    </div>

                    <a href="{% url 'show-detail' donc.id %}" class="btn btn-block btn-outline-info">Show desc </a>
                    
                </figcaption>

            </figure>

        </div> <!-- col.// -->

        {% endfor %}
    </div> <!-- row end.// -->

    <nav class="mt-4" aria-label="Page navigation sample">
    
        <ul class="pagination">

          <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
          <li class="page-item active"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item"><a class="page-link" href="#">Next</a></li>

        
        </ul>

      </nav>

        </main> <!-- col.// -->
    
    </div>
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}

service/templates/services/categoryfinal.html
{% extends 'homepages.html' %}

{% block content %}




<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container">
        <h2 class="title-page">Our Services</h2>
        
    </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->
    
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-md-3">
            <div class="card">
                <article class="filter-group">
                    <header class="card-header">
                        
                    </header>
                    <div class="filter-content collapse show" id="collapse_1" >
        
                        <div class="card-body">
        
                           
        
                        </div> <!-- card-body.// -->
        
                    </div>
        
                </article> <!-- filter-group  .// -->
        
            </div> <!-- card.// -->
            
     <!-- card.// -->
     
        </aside> <!-- col.// -->
        <main class="col-md-9">

    <header class="border-bottom mb-4 pb-3">

            <div class="form-inline">

                <span class="mr-md-auto"> {{counter}} Items found </span>

            </div>

    </header><!-- sect-heading -->

    <div class="row">

        {% for donc in service %}
        
        <div class="col-md-4">

            <figure class="card card-product-grid">

                <div class="img-wrap">

                    <img src="{{donc.image.url}}">

                </div> <!-- img-wrap.// -->

                <figcaption class="info-wrap">
                
                    <div class="fix-height">
                        
                        <a href="#" class="title"></a>
                        
                        <div class="price-wrap mt-2">

                            <span class="price">{{donc.Service_name}}</span>

                            <br>

                            <span class="price">baladiya: {{donc.baladiya}}</span>

                            <br>

                            <span class="price">{{donc.owner.first_name}} </span>

                            <span class="price">{{donc.owner.last_name}} </span>
      
                        </div> <!-- price-wrap.// -->

                    </div>

                    <a href="{% url 'show-detail' donc.id %}" class="btn btn-block btn-outline-info">Show desc </a>
                    
                </figcaption>

            </figure>

        </div> <!-- col.// -->

        {% endfor %}

    </div> <!-- row end.// -->
    
    
    <nav class="mt-4" aria-label="Page navigation sample">

      <ul class="pagination">

        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
        
      </ul>

    </nav>
    
     </main> <!-- col.// -->
    
    </div>
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}

service/templates/services/categoryproduct.html
{% extends 'homepages.html' %}

{% block content %}




<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container">
        <h2 class="title-page">Our Services</h2>
        
    </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->
    
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-md-3">
            <div class="card">
                <article class="filter-group">
                    <header class="card-header">
                        <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                            <i class="icon-control fa fa-chevron-down"></i>
                            <h6 class="title">Category  </h6>
                        </a>
                    </header>
                    <div class="filter-content collapse show" id="collapse_1" >
        
                        <div class="card-body">
        
                            <ul class="list-menu">
        
                                {% for cat in category %}
        
                            <li><a href="{% url 'categoryfinal' cat.id %}"> {{cat.Category_name}}  </a></li>
    
                            {% endfor %}
                            
                            </ul>
        
                        </div> <!-- card-body.// -->
        
                    </div>
        
                </article> <!-- filter-group  .// -->
        
            </div> <!-- card.// -->
            
     <!-- card.// -->
     
        </aside> <!-- col.// -->
        <main class="col-md-9">
    
    <header class="border-bottom mb-4 pb-3">
            <div class="form-inline">
                <span class="mr-md-auto"> {{counter}} Items found  </span>

            </div>
    </header><!-- sect-heading -->
    
    <div class="row">
        {% for donc in service %}

        <div class="col-md-4">

            <figure class="card card-product-grid">

                <div class="img-wrap">

                    <img src="{{donc.image.url}}">

                </div> <!-- img-wrap.// -->

                <figcaption class="info-wrap">
                
                    <div class="fix-height">
                        <a href="#" class="title"></a>
                        
                        <div class="price-wrap mt-2">

                            <span class="price">{{donc.Service_name}}</span>

                            <br>

                            <span class="price">baladiya: {{donc.baladiya}}</span>

                            <br>

                            <span class="price">{{donc.owner.first_name}} </span>

                            <span class="price">{{donc.owner.last_name}} </span>
      
                        </div> <!-- price-wrap.// -->

                    </div>

                    <a href="{% url 'show-detail' donc.id %}" class="btn btn-block btn-outline-info">Show desc </a>
                    
                </figcaption>

            </figure>

        </div> <!-- col.// -->

        {% endfor %}

    </div> <!-- row end.// -->
    
    
    <nav class="mt-4" aria-label="Page navigation sample">

      <ul class="pagination">

        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
        
      </ul>

    </nav>
    
     </main> <!-- col.// -->
    
    </div>
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}

service/templates/services/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}

<option value="{{ city.pk }}">{{ city.Category_name }}</option>

{% endfor %}

service/templates/services/createservice.html
{% extends 'homepages.html' %}

{% block content %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body">
            <header class="mb-4"><h4 class="card-title">Create service</h4></header>

            <form action="{% url 'create-service' %}" method="POST" enctype="multipart/form-data" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}">
                
                {% csrf_token %}

                    <div class="form-row">
                        <div class="col form-group">
                            <label>Service_name</label>

                            {{service.Service_name}}

                        </div> <!-- form-group end.// -->

                        <div class="col form-group">
                            <label>Description</label>
                            {{service.description}}
                        </div> <!-- form-group end.// -->

                    </div> <!-- form-row end.// -->
                    
                    
                    <div class="form-row">
                        <div class="form-group col-md-6">

                          <label>Select image for your Services  </label>

                          {{service.images}}
                          
                        </div> <!-- form-group end.// -->

                         <!-- form-group end.// -->
                    </div> <!-- form-row.// -->
               
                    <div class="form-row">
                        <div class="form-group col-md-6">
                          <label>your_sertificate </label>

                          {{service.your_sertificate}}

                        </div> <!-- form-group end.// -->

                         <!-- form-group end.// -->
                    </div> <!-- form-row.// -->
                    
                 <!-- form-row.// -->


                 <div class="form-row">

                    <div class="form-group col-md-6">

                      <label>select your baladiya </label>

                      {{service.baladiya}}

                    </div> <!-- form-group end.// -->
                    <!-- form-group end.// -->
                </div> <!-- form-row.// -->


                    <div class="form-row">

                        <div class="form-group col-md-6">

                          <label>select your category </label>

                          {{service.category}} 

                        </div> <!-- form-group end.// -->
                        <!-- form-group end.// -->
                    </div> <!-- form-row.// -->

                    
                    <div class="form-group">

                        <button type="submit" class="btn btn-primary btn-block"> Send  </button>

                    </div> <!-- form-group// -->      

                </form>

            </article><!-- card-body.// -->

        </div> <!-- card .// -->

        <br><br>



        
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_baladiya").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const baladiyaId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'baladiya_id': baladiyaId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_category").html(data);  // replace the contents of the city input with the data that came from the server
                /*
                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);
                */
            }
        });

    });
    
</script>


    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->


    {% if service.errors %}
    {% for field in service %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}

    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>

    {% endfor %}

    {% endif %}

    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
    



{% endblock %}